config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :blog
  resources :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/index.html.erb
<div class="row">
<!-- sidebar -->
  <div class="col-sm-2">
    <nav class="navbar navbar-light navbar-static bg-faded">
      <ul class="navbar-side" id="navbarSide">
          <h2 class="navbar-side-item">Archives</h2>
          <ul>
            <li class="side-link">March 2017</li>
            <li class="side-link">March 2017</li>
            <li class="side-link">March 2017</li>
            <li class="side-link">March 2017</li>
            <li class="side-link">March 2017</li>
            <li class="side-link">March 2017</li>
            <li class="side-link">March 2017</li>
            <li class="side-link">March 2017</li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
  
<!-- blog content -->
  <div class="col-sm-10" id="sidebar-padding">
    <header class="col-sm-10">
      <div class="header-content">
        <div class="header-content-inner">
          <h1 id="homeHeading">Blog</h1>
          <hr>
          <div class="blog-content">
            <h1>Stumptown</h1>
            <p>March 10, 2017</p>
            <p id="content">Beard stumptown listicle church-key. YOLO flexitarian, mustache tote bag food truck viral. Franzen freegan af XOXO paleo retro, sriracha prism ennui. Cornhole bicycle rights, cardigan biodiesel artisan gentrify yuccie portland tofu flexitarian art party.</p>
          </div>
        </div>
      </div>
    </header>
  </div>
</div>

app/views/contact/index.html.erb
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <h1 id="homeHeading">Contact Us</h1>
      <hr>
      <div class="row justify-content-center">
        <div class="col-sm-6">
          <form>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-group">
              <label for="exampleTextarea">Text</label>
              <textarea class="form-control" id="exampleTextarea" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-secondary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/home/index.html.erb
<!-- splash page content -->
<header class="initially-showing">
  <div class="header-content">
    <div class="header-content-inner">
      <h1 id="homeHeading">Kombucha scenester pitchfork portland air plant, cray health goth tofu street art thundercats ethical helvetica.</h1>
      <hr>
      <p>Beard stumptown listicle church-key. YOLO flexitarian microdosing, mustache tote bag food truck viral. Franzen freegan af XOXO paleo retro, sriracha prism ennui. Crucifix cornhole bicycle rights, cardigan biodiesel artisan gentrify yuccie portland tofu flexitarian art party.</p>
      <a id="show-form" class="btn btn-secondary btn-xl page-scroll">Sign Up!</a>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SitecastChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top">

  <!-- Collapsible Navbar -->
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand d-flex" href="/">Sitecast Challenge</a>
        <ul class="navbar-nav d-flex">
          <li class="nav-item">
            <%= link_to "Blog", blog_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_index_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

  <!-- templates -->
    <div class="container-fluid">
      <%= yield %>
    </div>
    
  <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; 2017 Caitlin Ashtari All rights reserved.</p>
      </div>
    </footer>
  </body>
</html>